[package]
name = "Cerddo-Pod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bass-sys = "2.3.0"
crossterm = "0.27.0"
ratatui = "0.26.2"
